### ISSUE TITLE
Application Review

### ISSUE THREAD

**Issue by nitinmetagovpm** [nitinmetagovpm/interop#1]
Timeline for the Application review is from May 31 2024 to July 15 2024

**Comment by nitinmetagovpm** [comment]
### Application Review Tasks
- [ ] [Initial Screening](#2 )
- [ ] [Review of Application by main reviewers](#3 )
- [ ] [Meeting 1 to discuss applications](#4 )
- [ ] [Meeting 2 to discuss applications](#5 )
- [ ] [Grant Approval/ Rejection Letters](#6 )
